# Config file for automatic testing at travis-ci.com

language: python
dist: xenial

branches:
  only:
  - master
  - develop

matrix:
  include:
    - python: '3.6'
      env:
        - TOXENV=py36
    - python: '3.7'
      env:
        - TOXENV=py37
    - python: '3.7'
      env:
        - TOXENV=docs
    - python: '3.7'
      env:
        - TOXENV=linter

install:
  - pip install tox

script:
  - tox
