# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7

# Command to run tests, e.g. python setup.py test
install:
- pip install pipenv
- pipenv install --system --deploy --ignore-pipfile

branches:
  only:
  - master
  - develop

stages:
  - test

jobs:
  include:
    - stage: test
      script: pytest -v
      install:
        - pip install pipenv
        - pipenv install --system --deploy --dev --ignore-pipfile
