# Config file for automatic testing at travis-ci.com

language: python
dist: xenial
matrix:
  include:
    - python: '3.6'
      env:
        - TOXENV=py36
    - python: '3.7'
      env:
        - TOXENV=py37
    - python: '3.7'
      env:
        - TOXENV=docs

# Command to run tests, e.g. python setup.py test
install:
- pip install pipenv
- pipenv install --system --deploy --ignore-pipfile

branches:
  only:
  - master
  - develop

stages:
  - test

jobs:
  include:
    - stage: test
      script: pytest -v
      install:
        - pip install pipenv
        - pipenv install --system --deploy --dev --ignore-pipfile
